language: generic

jdk:
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - mvn clean cobertura:cobertura -Dmaven.test.skip=false

after_success:
  - bash <(curl -s https://codecov.io/bash)